### ISSUE TITLE
[BUG] Could not pass event BlockPhysicsEvent to ItemsAdder v2.4.6

### ISSUE THREAD

**Issue by EchocallingEarth** [PluginBugs/Issues-ItemsAdder#1075]
**Describe the bug**
Unsure of what caused the bug or how to reproduce but will provide any and all info needed in order to hopefully find a resolution.

**To Reproduce**
Console Error - no in chat message logged

**Expected behavior**
[19:27:26] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.4.6
java.lang.ClassCastException: class dev.lone.itemsadder.Core.e.f cannot be cast to class dev.lone.itemsadder.Core.e.m (dev.lone.itemsadder.Core.e.f and dev.lone.itemsadder.Core.e.m are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @71fb9f9d)
	at dev.lone.itemsadder.Core.f.a.b.b.b.b.a(SourceFile:117) ~[?:?]
	at dev.lone.itemsadder.Core.f.a.b.b.b.b.a(SourceFile:53) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1287]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1287]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1287]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:740) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:693) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:602) ~[?:?]
	at net.minecraft.world.level.Level.setBlockAndUpdate(Level.java:813) ~[?:?]
	at net.minecraft.world.entity.LightningBolt.spawnFire(LightningBolt.java:187) ~[?:?]
	at net.minecraft.world.entity.LightningBolt.tick(LightningBolt.java:99) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1186) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:803) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:784) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1287]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1287]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[19:32:15] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.4.6
java.lang.ClassCastException: null

**Screenshots**

**Info (please complete the following information):**
 - Purpur 1.17.1
 - N/A

**Special Info**
Please do not write "latest"! Tell us the specific plugin version you are using.
 - ItemsAdder v2.4.6
 - LightAPI Fork 3.5.2
 - LoneLibs 1.0.14
 - ProtocolLib build 531 (released Jul 27, 2021 6:52:08 AM)

**Additional context**
Full log upon request
Plugins: AdvancedChests, AdvancedClaimGuardian, AdvancedEnchantments, AntiCurse, ArmoredElytra, AureliumSkills, Bank, BigDoors, BlockParticles, ChestSort, Chunky, Citizens, CleanroomGenerator, CMI, CMIEInjector*, CMILib, ConsoleSpamFix, Core, CoreProtect, CustomCrafting, CustomEnderChest, CustomShop, Denizen, DisplayShops, dtlTradersPlus, EpicBackpacks, EpicFarming, EpicFurnaces, EpicHoppers, ExoticGarden, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), HeadDatabase, HolographicDisplays, HorseOverhaul, ImageOnMap, InfoBook, Item-Chest-Sorter, ItemsAdder, Jobs, LibsDisguises, LightAPI, LimitPillagers, LoneLibs, Lootin, LuckPerms, LWC, Multiverse-Core, NBTAPI, NetheriteShield, NoPlugins, PerWorldInventory, PlaceholderAPI, ProtocolLib, PublicCrafters, Sentinel, Slimefun, spark, SuperLuckyBlock, SurvivalInvisiframes, Terra, UltimateCatcher, UltimateFishing, UltimateRepairing, UltimateStacker, UltimateTimber, VanillaTweaks, Vault, WolfyUtilities

**Comment by Rushia140** [comment]
Now that's not the case, when I fixed some bugs in tools.yml, I'm sure

**Comment by EchocallingEarth** [comment]
So I received an email response regarding this but I am unsure of how I should read it. Does it mean you have fixed it or it should be fixed? Or could it be a 1-time bug that I will monitor for and hope for the best?

Please clarify, thank you.

"Email as sent (although the response is not showing here for whatever reason).
Rushia140 <notifications@github.com>
To: PluginBugs/Issues-ItemsAdder
Cc: EchocallingEarth, Author
Thu, Jul 29 at 5:36 AM
_Now that's not the case, when I fixed some bugs in tools.yml, I'm sure_"

Email screen clip attached to ensure accuracy.
<img width="602" alt="github" src="https://user-images.githubusercontent.com/47970978/127728089-f5e52bd7-3d86-4102-8c63-21fcfc04d672.PNG">

Again any info I can provide that may help in any way I will provide.

**Comment by LoneDev6** [comment]
@EchocallingEarth I have no idea of what this user Rushia140 was talking about. I'm the developer of the plugin and I'm answering now.
This error may be thrown due to bad loading of an item, recipe or something else.
I suggest you to check the initial itemsadder loading log to check if something wrong is shown.

Anyway I'll catch this error in the future updates and show a clear notice of why it's triggered.

Have a nice day

**Comment by LoneDev6** [comment]
This error can be safely ignored.
It's because a custom fire was removed from configurations but still exists in the world.
I will publish an update that will suppress this error since it's just a warning, it won't cause problems ingame, don't worry.
