### ISSUE TITLE
Betterranks and old texturepack compatibility

### ISSUE THREAD

**Issue by EPGMooky** [PluginBugs/Issues-ItemsAdder#2158]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

EPGMooky#2597

### What happened?

I tried the merge separately addon betterranks and they didn't work.
Finally I tried to merge an old resourcepack where I had these ranks and it popped up a bunch of errors that I can't identify

Thank you for your help!

### Steps to reproduce the issue

1. Betterranks merge.
2, ranks always shows this symbol  [].

### Server version

Current: git-Purpur-1857 (MC: 1.19.2)*
Previous: git-Purpur-1845 (MC: 1.19.2)
* You are running the latest version

### ItemsAdder Version

3.3.0-beta-r10

### ProtocolLib Version

5.0.0-SNAPSHOT-b600

### LoneLibs Version

1.0.21

### Error (optional)

```shell
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/rpg.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/creative.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/economy.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/vanilla.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/offline.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/tags/online.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/srsupport.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/hbuilder.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/developer.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/support.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/exarch.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/zealot.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/builder.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/esupport.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/hsupport.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/manager.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/influencer.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/mentor.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/dreenal.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/patron.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/booster_logo.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/booster.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/neophyte.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/player.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/tsupport.png[0m
[14:00:27] [Craft Scheduler Thread - 36 - ItemsAdder/ERROR]: [ItemsAdder] [0m[38;5;9mInvalid character in namespace 'Allerial' of file: /contents/Allerial/assets/betterranks/textures/font/rank/moderator.png[0m
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/42835070/205062556-5da92c79-15bc-4444-9153-632b0404f942.png)

**Comment by Akiranya** [comment]
The actual issue is that IA 3.3 enforces the namespace rule according to the standard of Minecraft resourcepack. That is, namespace must be all lowercase and can only contains `_` and numbers.

Change `Allerial` to `allerial` should resolve this issue.

**Comment by EPGMooky** [comment]
Yes, thanks!! This resolve namespace problem. But betterranks still dont work and show only [] [] <---this

**Comment by EPGMooky** [comment]
![image2](https://user-images.githubusercontent.com/42835070/205284083-ff1119bd-2be0-4711-8b74-9402fff51b27.png)
![image](https://user-images.githubusercontent.com/42835070/205284089-33bcfc41-d3a6-46f2-bfbc-ea8eb92f5788.png)

**Comment by EPGMooky** [comment]
I I tried these placeholders: :admin: %img_admin%

**Comment by Akiranya** [comment]
Have a look at the new file structure of IA 3.3+: https://itemsadder.devs.beer/3-3-vs-3-2

You need to migrate your old betterrank files into the new structure. The same applies to any other pack you have.

**Comment by LoneDev6** [comment]
> Have a look at the new file structure of IA 3.3+: https://itemsadder.devs.beer/3-3-vs-3-2
> 
> You need to migrate your old betterrank files into the new structure. The same applies to any other packs you have.


Migration is not mandatory, the old structure will still load fine.
There is something else broken here.
Check your server console for errors, if you still cannot load the font images read here:
https://itemsadder.devs.beer/faq/identify-why-textures-are-not-shown

**Comment by EPGMooky** [comment]
It worked until the new version.. that acctually fix the space problem  but broken everything else. 

If i create new "config" folder a put it togedher with textures it fixed like half of the tags. Not all of them for some reason. 

I don't understand how only some textures can work?
![obrazek](https://user-images.githubusercontent.com/42835070/205323955-55dbbe0f-81f3-441f-aff7-866df3684e19.png)

**Comment by EPGMooky** [comment]
[12:52:36] [Worker-Main-8/WARN]: Unable to load font 'minecraft:default' in fonts.json in resourcepack: 'c6a68722d0e33acb184ab50655052d285884471d'
java.lang.RuntimeException: minecraft:textures/custom/logo.png
	at ejn$a.create(SourceFile:132) ~[1.19.2.jar:?]
	at eje$1.a(SourceFile:77) ~[1.19.2.jar:?]
	at eje$1.b(SourceFile:46) ~[1.19.2.jar:?]
	at air.a(SourceFile:11) ~[1.19.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by EPGMooky** [comment]
java.lang.RuntimeException: betterranks:textures/font/rank/booster_logo.png
	at ejn$a.create(SourceFile:132) ~[1.19.2.jar:?]
	at eje$1.a(SourceFile:77) ~[1.19.2.jar:?]
	at eje$1.b(SourceFile:46) ~[1.19.2.jar:?]
	at air.a(SourceFile:11) ~[1.19.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by EPGMooky** [comment]
I dont really know what this mean

**Comment by Akiranya** [comment]
Have you tried **just** fixing the uppercase namespace but leaving the rest of files **intact**?

As LoneDev said, the old structure `data` still works and you don't need to migrate to the new structure for the time being.

**Comment by EPGMooky** [comment]
Looks like i fixed it. My old Minecraft:default font dont like new merge system... so i regenerate it by the new system and it work

**Comment by EPGMooky** [comment]
Thanks for help Lone and Akiranya!

**Comment by EPGMooky** [comment]
Thanks for help Lone and Akiranya!

**Comment by LoneDev6** [comment]
Happy everything works fine now!
I'm always happy when my customers are satisfied.
I hope you will consider leaving a good review :) it would help me to stay motivated and continue delivering updates.
