### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by Naghell** [PluginBugs/Issues-ItemsAdder#2185]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### Discord tag (optional)

Naghell#9778

### What happened?

I added ItemsAdder to my server, along with CosmeticsCore, following the installation guide to the letter. I can't get the plugin to start, and the error message isn't very explanatory.

I use the latest version of the plugin, from LoneLibs and LibsDisguises. I tried with other versions of all the plugins, looking for some combination that works but I can't get anything.

### Steps to reproduce the issue

.

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-271 (MC: 1.19.2)

### ItemsAdder Version

ItemsAdder version 3.3.0
Customized Minecraft without client mods!
Website: devs.beer
Author: LoneDev

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b607

### LoneLibs Version

LoneLibs version 1.0.21

### LightAPI Version (optional)

I added the latest version, 5.3.0, but it wouldn't load the plugin for some reason so I removed it.

### LibsDisguises Version (optional)

LibsDisguises version 10.0.31 (PREMIUM)

### Error (optional)

```shell
[20:44:03] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.3.0
[20:44:04] [Server thread/INFO]: [ItemsAdder] [m[0;36;1m
[0;36;1m  ___  ___        __        __   __   ___  __  [0;32;22m    ItemsAdder[0;37;22m 3.3.0
[0;36;1m|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__) [0;32;22m    LoneLibs[0;37;22m 1.0.21
[0;36;1m|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \ [0;30;1m    Paper git-Paper-307 (MC: 1.19.2)
[0;36;1m                                               [m
[20:44:04] [Server thread/INFO]: [ItemsAdder] [m[0;33;1mLightAPI not installed, please install it to see blocks emitting light: [0;36;1mhttps://a.devs.beer/lightapi-new[m
[20:44:04] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v3.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ia.m.I
	at dev.lone.itemsadder.Main.onEnable(SourceFile:434) ~[ItemsAdder_3.3.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:44:04] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v3.3.0
```

**Comment by LoneDev6** [comment]
Download the jar again.
Seems it's corrupted. Probably partial download or partial upload to server.

**Comment by Naghell** [comment]
I did several tests, uploaded it in different versions and even in the last one a few more times. It's not a partial download or partial upload problem. Anyway, I tried downloading it again, renaming it, uploading different files and they all have the same size.

**Comment by Naghell** [comment]
The problem is when starting ItemsAdder with CosmeticsCore. ItemsAdder works only if it is not CC. Without it, it starts without error.

**Comment by lmichaelz** [comment]
Having the same issue, itemsAdder loads fine on its own. If enabling CosmeticsCore then getting the same bug as mentioned by OP.

**Comment by LoneDev6** [comment]
Redownload both plugins, I tested their last version and they load fine on my servers.

**Comment by Naghell** [comment]
To confirm, and to check if the file was downloaded wrong the other 25 times, I re-downloaded everything and put it back. It doesn't work with CosmeticsCore.

**Comment by lmichaelz** [comment]
Tried it as well again, does not work with CosmeticsCore. Running with same plugin versions and dependencies as OP.

**Comment by dinobossytnew** [comment]
@LoneDev6 x2

**Comment by dinobossytnew** [comment]
I still can't fix it and I can't live downloaded it keeps happening on localhost as well.

**Comment by LoneDev6** [comment]
Send the whole log then.
Based on the error you included I can only tell you that the JAR doesn't contains some needed parts, this is caused by a broken downloaded file.
If that would be a bug then I'd have other 300 reports, but it happens only on your server.
So please, post your complete log.

Also try removing all other plugins and see if the error occurs.

**Comment by Naghell** [comment]
[2022-12-20-7.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10280352/2022-12-20-7.log)

**Comment by Naghell** [comment]
MythicMobs is the problem. In its version 5.1, 5.2.0 and 5.2.1 dev.

**Comment by lmichaelz** [comment]
On my end, I disabled Mythic mobs (and other mythiccraft suite plugins) and it is still creating errors on startup.

[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/10284479/latest.1.log)

**Comment by LoneDev6** [comment]
Remove all plugins until you find the cause.
It's impossible for me to identify the issue since the log has no errors other that some about missing dependencies (which you should really fix tbh).

The error thrown by ItemsAdder is about the fact that a part of the plugin cannot be found and this happens when JAR is corrupted because of a partial download, so that's all I can say based on what you sent.

**Comment by MrDraqon** [comment]
> 

I am also having this issue, seems like CosmeticsCore is being loaded before ItemsAdder
Not sure why this would happen, i tested it on another server and it works fine there weird issue

**Comment by LoneDev6** [comment]
This has been fixed on latest CosmeticsCore, feel free to download it and check :D

**Comment by MrDraqon** [comment]
> 

CosmeticsCore loads now but items adder still fails to enable same error as the initial OP

**Comment by MrDraqon** [comment]
> A similar issue has been fixed on latest CosmeticsCore, feel free to download it and check :D [PluginBugs/Issues-CosmeticsCore#73](https://github.com/PluginBugs/Issues-CosmeticsCore/issues/73) Let me know

Okay tried deleting plugins until it worked, didnt really get anywhere 


so for itemsadder to work with CosmeticsCore installed
I have to delete all plugins from C > A 
and Plugins from E > D

Odd thing is i can leave some plugins like essentialsx and DragonTagsV2
Those can stay but every other plugin that starts with those letters will break ItemsAdder When CosmeticsCore is installed
If i remove CosmeticsCore then ItemsAdder works fine with all other plugins

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-CosmeticsCore/issues/79#issuecomment-1377424765

**Comment by MrDraqon** [comment]
> Please test the new r3 update. This is extremely strange to be honest... something's wrong on your server definitely.
> 
> Download here: https://www.spigotmc.org/resources/cosmeticscore.105324/

Still the same issue, never seen this before its super weird like been trying for 3 hours now deleting plugins from E > A 
and made a list of possible plugins but when remove those it still does it, so i make another list of the remaining plugins and just end up with all of them as the issue. No idea how else to debug this issue its super weird

If you want i can give you panel access i think you gotta experience to understand how odd it is xD

**Comment by LoneDev6** [comment]
@MrDraqon  Try r4, my beta testing team now confirmed that the issue vanished on their server.

**Comment by MrDraqon** [comment]
> @MrDraqon Try r4, my beta testing team now confirmed that the issue vanished on their server.

Yeah that fixed it awesome! thank you!

**Comment by LoneDev6** [comment]
@MrDraqon I hope you will consider leaving a 5 stars review, it would help me so much considering the latest bad reviews my product received 😓
https://www.spigotmc.org/resources/73355/
Thanks a lot!

**Comment by MrDraqon** [comment]
> @MrDraqon I hope you will consider leaving a 5 stars review, it would help me so much considering the latest bad reviews my product received 😓 https://www.spigotmc.org/resources/73355/ Thanks a lot!

Cant leave one on ItemsAdder me and a friend are making a server and hes the one who bought ItemsAdder i bought CosmeticsCore but i am sure i can write a review and tell him to post it 😃
