### ISSUE TITLE
PROBLEM PERMISSION USING EMOJI IN CHAT

### ISSUE THREAD

**Issue by niriaaa** [PluginBugs/Issues-ItemsAdder#2330]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

niria#0001

### What happened?

Hello,

Players are able to use emojis or even font images in the general chat without even having the permissions.

By writing in the chat :poo: it tells them that they don't have the permissiuon but if they do ::poo:: then the emoji appears.

I try on my dev server with the last update and same problem.

Thanks

### Steps to reproduce the issue

- Players are able to use emojis or even font images in the general chat without even having the permissions.
- By writing in the chat :poo: it tells them that they don't have the permissiuon but if they do ::poo:: then the emoji appears.

### Server version

purpur 1884 (version 1.19.3)

### ItemsAdder Version

Itemsadder version 3.3.0b-r5

### ProtocolLib Version

ProtocolLib version 5.0.0 SNAPSHOT-b608

### LoneLibs Version

Lonelibs version 1.0.22

**Comment by niriaaa** [comment]
Hello, any news please?

I report this of the forum and you tell me to report here, and we are still wainting...

Thanks
Niriaa

**Comment by LoneDev6** [comment]
Update itemsadder when you report issues, most of the times they were already fixed.

**Comment by TnTVlogs** [comment]
Hi, I know it's closed and I'm sorry but still happens to me on version [3.4.1-r5] of IA, Purpur 1.19.3, LoneLibs 1.0.24, any solutions? Could be Purpur 1.19.3?
Thanks and sorry again

**Comment by LoneDev6** [comment]
@TnTVlogs 
Please provide more information about your server.
Like which chat plugin are you using, video of the issue and full server log.

Anyway it's not generally good to comment on other customers issue reports if they are closed months ago. This would notify when about activity.

Have a nice day.

**Comment by TnTVlogs** [comment]
Im using Purpur 1.19.3-1933, latest Items Adder and LoneLibs, I was using ChatManager plugin for chat, I changed it to normal EssentialsChat, and still the same problem. Plugins that may conflict with chat could be NoEncryption 1.19.3-5.1. I have '*' permissions and this does not affect to me, but the default people can write ::heart:: and it appears the emoji. And that's it, sorry again to write on this closed issue.

SERVER LOG: [LOG](https://pastebin.com/3ywNQwQn)

https://user-images.githubusercontent.com/46499704/232843381-227ac183-99a2-4b3f-8d9a-7d50df85e7aa.mp4

**Comment by LoneDev6** [comment]
I'll do some tests and let you know, very strange

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2555
