### ISSUE TITLE
furnitures delete projectile

### ISSUE THREAD

**Issue by aaa8881** [PluginBugs/Issues-ItemsAdder#2552]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

signition#0001

### What happened?

furnitures delete all projectile when being hit. 

trident, arrow, anything

### Steps to reproduce the issue

1. place furniture
2. launch projectile to its hitbox

### Server version

pufferfish 47 (1.19.3)

### ItemsAdder Version

3.4.1-r5

### ProtocolLib Version

#616

### LoneLibs Version

1.0.24

### FULL server log

no log

### Error (optional)

```shell
no error
```

### Other files, you can drag and drop them here to upload. (optional)

check video please. it's obvious
tried with different furnitures as well. all same. 

### Screenshots/Videos (you can drag and drop files or paste links)

https://www.youtube.com/watch?v=PzaBnCy8wZk

**Comment by LoneDev6** [comment]
This was fixed a lot of time ago.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1093

NOTE: the fix works only on Paper and its forks, not on Spigot, because Spigot lacks of an important method [getItemStack()](https://jd.papermc.io/paper/1.17/org/bukkit/entity/AbstractArrow.html#getItemStack()).
As you can see Spigot lacks of this method: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/AbstractArrow.html

**Comment by aaa8881** [comment]
but it happens for me.
I just tried updating to 3.4.1-r6 from 3.4.1-r5 ( which is not that old version ) , and issue still persists.

**Comment by aaa8881** [comment]
bukkit is pufferfish-61 ( based on 1.19.3 paper )

**Comment by LoneDev6** [comment]
I will do some tests. It worked just fine last time I tested.
Thanks for the patience.

**Comment by LoneDev6** [comment]
Fixed in the upcoming update, thanks!
Related to this: https://github.com/PluginBugs/Issues-ItemsAdder/issues/2661
