### ISSUE TITLE
1.20.1 client can't break custom blocks

### ISSUE THREAD

**Issue by BredyAK** [PluginBugs/Issues-ItemsAdder#4431]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

henry_crown

### What happened?

Players on 1.20.1 client can't break `REAL_WIRE` blocks on Paper-1.21.4 server.

https://github.com/user-attachments/assets/23606035-c79c-412d-802b-64d6ba09a789

### Steps to reproduce the issue

1. Define any custom block with ItemsAdder on Paper-1.21.4 server.
2. Enter your server with Minecraft 1.20.1 client. (Require the server install `ViaVersion` and `ViaBackwards`)
3. Try to break the block you defined on step 1, you'll find it can't be broken unless move your cursor out of the block you are breaking. (Check the video i uploaded)

### Server version

Paper-1.21.4-150

### ItemsAdder Version

4.0.9-beta-5

### ProtocolLib Version

5.4.0-SNAPSHOT-741

### LoneLibs Version

Not installed, because the ItemsAdder said it's not needed anymore.

### Full Server Log

https://mclo.gs/ZaDNimn

### Error (optional)

No errors.

### Problematic items yml configuration file (optional)

`pepples.yml`:

```yaml
info:
  namespace: test
items:
  pebbles:
    enabled: true
    display_name: pebbles-display-name
    resource:
      material: PAPER
      generate: false
      model_id: 1
      model_path: minecraft:item/generated
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          break_particles: BLOCK
        drop_when_mined: true
        hardness: 0.5
        blast_resistance: 0.5
        sound:
          break:
            name: minecraft:internal.block.stone.break
            volume: 1.0
            pitch: 1.2
          place:
            name: minecraft:internal.block.stone.place
            volume: 1.0
            pitch: 1.2
          hit:
            name: minecraft:internal.block.stone.hit
            volume: 0.25
            pitch: 0.8
          step:
            name: minecraft:internal.block.stone.step
            volume: 0.15
            pitch: 1.0
          fall:
            name: minecraft:internal.block.stone.fall
            volume: 0.5
            pitch: 0.75
```

**Comment by Andre601** [comment]
This is most likely not an ItemsAdder issue itself.

For once is the plugin running on 1.21.4, so the resource pack is also specifically generated against this version.
Next is v4 of ItemsAdder designed for versions 1.20.6 upwards, so 1.20.4 is none of its supported versions.
And finally is support for clients with different versions generally not a supported thing by ItemsAdder. The plugin doesn't do any special handling for those and leaves it to the Via* plugins to handle, as they are responsible for handling the incoming and outgoing packets of these players.

Due to these reasons will I close this issue. Feel free to request it getting re-opened **IF** the issue can be reproduced on a server setup as described in #4187, meaning without Via* plugins or any other plugin for that matter.
(Another reason for closing is the fact you ignored the Checks you have agreed to have followed, which you didn't do for at least the last checkbox).

**Comment by BredyAK** [comment]
> Why are your players joining with a minor version? You should really open ViaVersion configuration and do not allow all versions to join but only major versions. What I'd do is allow only 1.19.4, 1.20.4, 1.20.6 and 1.21.4, but generally there is absolutely no advantage in having a multi-version server as it just degrades the player experience and also makes your life harder.
> 
> Anyway, can you test with 1.20.4 client?

Hi there LoneLev6! I've carefully read your article of [this](https://itemsadder.devs.beer/itemsadder-v4#viaversion-madness) and totally understand your concerns. I also hope my players to use the latest version of Minecraft client. But I can't, since I'm in China, and my server is running on Minecraft China Edition, the client versions that players can currently use are up to 1.20.1 only. As for the reason, you can go to [Minecraft Wiki](https://minecraft.wiki/w/China_Edition) to learn more. In short, this is the regulation made by Mojang and NetEase for the Chinese players that I cannot change.

I really like ItemsAdder beucase it gives me endless possibilities and creativity, but due to the backwardness of the China Edition, I have to endure many problems caused by cross-version. I have tried my best to circumvent these problems, but there are some problems that I cannot solve, such as the issue I am currently reporting.

Even if my issue could be marked as not planned in the end, I hope to fight for this opportunity for Chinese players, because I also hope that ItemsAdder can get better and better.

Thanks for your answer and your amazing work, and wish you and the dev team a nice day! :D

**Comment by BredyAK** [comment]
BTW, I have find a temp solution of this issue, that is setting the custom block's hardness to `-1`. This will cause players instantly break the block, and the block drops work just fine for me.

**Comment by LoneDev6** [comment]
This happens because you're not supposed to join a 1.20.5+ server with a 1.20.4 and lower client, because the client has some missing features, in this example it lacks of the `block_break_speed` attribute introduced in 1.20.5 (read more [here](https://minecraft.wiki/w/Attribute)).

**Comment by BredyAK** [comment]
> This happens because you're not supposed to join a 1.20.5+ server with a 1.20.4 and lower client, because the client has some missing features, in this example it lacks of the `block_break_speed` attribute introduced in 1.20.5 (read more [here](https://minecraft.wiki/w/Attribute)).

Thank you for the reply. I guess my issue could be fixed if there was an option such as `items.<block>.specific_properties.block.break_speed` to customize custom the block's breaking speed? Here is an example:

```yaml
info:
  namespace: myitems
items:
  red_block:
    display_name: Red Block
    resource:
      generate: true
      material: PAPER
      textures:
        - block/red_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_speed: 1
```

Do you think this would be alright? Then this issue could be converted to a feature request. :D

**Comment by LoneDev6** [comment]
Not that simple.
Anyway I currently have fixed the bug that would make any custom block unbreakable (break animation completes, but block appears again).

I also fixed the reported issue with `REAL_WIRE` blocks, but keep min mind that it's a workaround in this case. `REAL_WIRE` blocks will be broken immediately on 1.20.4 and lower clients, because there is currently no other way to fix that.

**Comment by BredyAK** [comment]
Not work, the issue still exist on version `4.0.9-beta-7`. Nothing changed.

> Not that simple. Anyway I currently have fixed the bug that would make any custom block unbreakable (break animation completes, but block appears again).
> 
> I also fixed the reported issue with `REAL_WIRE` blocks, but keep min mind that it's a workaround in this case. `REAL_WIRE` blocks will be broken immediately on 1.20.4 and lower clients, because there is currently no other way to fix that.

**Comment by LoneDev6** [comment]
You might have been using the wrong tool.
If you want users to be able to break the blocks even with wrong tool you have to set this in `config.yml`:

```yml   
cancel-break-wrong-tool:
    enabled: false
```


https://github.com/user-attachments/assets/fc8b0f04-abcd-4dad-9137-75de02e5bd2a

**Comment by BredyAK** [comment]
I can't break the block even if I have set `cancel-break-wrong-tool.enabled` to `false` in `config.yml`, and I don't think that's the reason. You could try my custom block as below:
```Yaml
info:
  namespace: minez
items:
  pebbles_small:
    enabled: true
    display_name: pebbles-display-name
    resource:
      material: PAPER
      generate: false
      model_id: 4
      model_path: minecraft:item/generated
    specific_properties:
      block:
        placed_model:
          type: REAL_WIRE
          break_particles: BLOCK
        drop_when_mined: true
        hardness: 0.5
        blast_resistance: 0.5
        sound:
          break:
            name: minecraft:internal.block.stone.break
            volume: 1.0
            pitch: 1.2
          place:
            name: minecraft:internal.block.stone.place
            volume: 1.0
            pitch: 1.2
          hit:
            name: minecraft:internal.block.stone.hit
            volume: 0.25
            pitch: 0.8
          step:
            name: minecraft:internal.block.stone.step
            volume: 0.15
            pitch: 1.0
          fall:
            name: minecraft:internal.block.stone.fall
            volume: 0.5
            pitch: 0.75

```

**Comment by LoneDev6** [comment]
I have no access to the chinese version of Minecraft due to restriction. I am testing with:
- Vanilla 1.20.1 client
- 1.21.4 Paper `1.21.4-138-main@5395ae3 (2025-02-02T21:42:11Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)`
- ViaVersion version 5.2.1
- ViaBackwards version 5.2.1
- Latest ItemsAdder version 4.0.9 beta version https://discord.com/channels/533407895010803753/1336644246849060926/1345041405352874096

**Comment by LoneDev6** [comment]
It is normal as it is required for custom blocks hardness to work.
It can not be hidden because of how the game works, there is no way to apply a potion effect and hide it from inventory sadly.

What I can do is change the high duration to `∞`
